# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8af1e6bac8d4c442e4267b7fe48c25d48a5b0a037bf2949a7dd4e2659781f53cc26293bdf67b20443ebb208f579a8899efe9b0091fe6ed6f874c361cc8efa68

test:
  secret_key_base: 5fc090d511edaa5f08b6c9680b1b06f79a1e557edb8673f3b4f3d528d2f3c5c56d004d7fb2892df567a43372c38af055af359ff70729d079637dab759dc89c29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
